server:
  port: 8083

spring:
  thymeleaf:
    prefix: classpath:/templates/ # 访问template下的html文件需要配置模板，映射，路径指向
    suffix: .html
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    encoding: UTF-8
    # 模板的模式
    mode: HTML5

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: cyq123456
  mvc:
    static-path-pattern: /**
  logging:
    level:
      root: warn
      com:
        example:
          compus:
            controller: debug
            dao: debug
mybatis:
  mapper-locations: classpath:/mapper/*.xml



